name: Build and Release Stable

on:
  push:
    # complemented with branch protection on main this will 
    # run on any pull request merge
    branches: main 

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        target: x86_64-unknown-linux-musl
        toolchain: nightly

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-release2-${{ hashFiles('**/Cargo.lock') }}

    - uses: actions-rs/cargo@v1
      with:
        use-cross: false
        command: build
        args: --release

    - name: Upload
      uses: actions/upload-artifact@v3
      with: 
        name: rbtw
        path: target/release/rbtw

    - name: get package version and tag.
      id: version_tag
      uses: dante-signal31/rust-app-version@v1.0.0
    outputs:
      package_tag: ${{ steps.version_tag.outputs.app_version }}

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download binaries
      uses: actions/download-artifact@v3
      with:
        name: rbtw
    - name: Release
      uses: "softprops/action-gh-release@v1"
      with:
        prerelease: true
        name: "x86 binary"
        files: rbtw
        tag_name: ${{needs.build.outputs.package_tag}}
